name: Keep Alive Ping

on:
  schedule:
    - cron: "*/5 * * * *"   # jalan tiap 5 menit (UTC)
  workflow_dispatch:         # 🔥 ini buat tombol "Run workflow" manual

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Curl to keep alive
        run: curl -s https://e7f29376-c150-42de-a009-37892af4c869-00-csw8qn9q0xl5.sisko.replit.dev/ > /dev/null
